language: node_js

node_js:
  - "4"
  - "5"
  - "6"

before_script:
  - npm install -g mocha
  - npm install -g gulp

before_install:
  - "npm install -g npm@latest"

install:
  - npm install

script:
  - npm test

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
